Repository liquality/wallet-sdk, pull requests merged in 2023-03, with the labels that each got.

#74 feat: support injected signer
  .changeset/soft-turkeys-tap.md
  packages/sdk/src/common/utils.ts
  packages/sdk/src/erc20/erc.service.ts
  packages/sdk/src/nft/nft.service.ts
  packages/sdk/src/swap/debridge/debridgeSwapProvider.ts
  packages/sdk/src/transaction/transaction.service.ts
Labels: ✅ Approved, size/M

#78 Fixes
  .changeset/rich-crabs-tickle.md
  packages/sdk/src/swap/debridge/debridgeSwapProvider.ts
Labels: 🔍 Ready for Review, size/S

#80 Add method to get native balance in account service
  .changeset/wise-emus-shake.md
  packages/sdk/src/account/account.service.ts
  packages/sdk/src/index.ts
Labels: 🔍 Ready for Review, size/S

#82 fix import path error
  .changeset/spicy-comics-teach.md
  packages/sdk/src/account/account.service.ts
Labels: 🔍 Ready for Review, size/XS

#88 fix: resolve build issue
  .changeset/selfish-rats-smash.md
  apps/web-demo/src/App.tsx
Labels: 🔍 Ready for Review, size/M

#90 fix: resolve build error
  .changeset/slimy-ears-knock.md
  apps/web-demo/src/App.tsx
Labels: 🔍 Ready for Review, size/XS

#95 Quick fix: Default to set gas, if gas estimate fails
  .changeset/early-moose-buy.md
  apps/web-demo/src/App.tsx
  packages/sdk/src/transaction/transaction.service.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/XXL

#100 fix: return raw metadata of nft
  packages/sdk/src/nft/providers/alchemy-nft.provider.ts
  packages/sdk/src/nft/types/index.ts
Labels: ✅ Approved, size/XS

#102 fix: use chainID of ExternalProvider param if exist
  packages/sdk/src/common/utils.ts
  packages/sdk/src/erc20/erc.service.ts
  packages/sdk/src/nft/nft.service.ts
  packages/sdk/src/swap/debridge/debridgeSwapProvider.ts
Labels: 🔍 Ready for Review, ✅ Approved, size/M
