Repository liquality/wallet-sdk, pull requests merged in 2023-02, with the labels that each got.

#9 Feat/list account tokens
  .gitignore
  packages/sdk/package.json
  packages/sdk/src/erc20/erc.service.ts
  packages/sdk/src/erc20/types/index.ts
  packages/sdk/src/index.ts
  packages/sdk/src/nft/nft.service.ts
  packages/sdk/src/transaction/transaction.service.ts
Labels: ✅ Approved, size/L

#10 feat: add swap by debridge
  packages/sdk/package.json
  packages/sdk/src/common/utils.ts
  packages/sdk/src/swap/debridge/abi/SignatureVerifier.json
  packages/sdk/src/swap/debridge/config.ts
  packages/sdk/src/swap/debridge/debridgeSwapProvider.ts
  packages/sdk/src/swap/debridge/types/index.ts
  packages/sdk/tsconfig.json
  yarn.lock
Labels: 🔍 Ready for Review, size/XXL

#14 fix release error
  .changeset/forty-bugs-call.md
  .github/workflows/release.yml
  package.json
Labels: 🔍 Ready for Review, size/S

#16 reset wallet version
  .changeset/shy-knives-deliver.md
  package.json
  packages/sdk/package.json
Labels: 🔍 Ready for Review, size/S

#18 Chore/automate release
  .changeset/tasty-coats-grab.md
  apps/web-demo/README.md
  apps/web-demo/config-overrides.js
  apps/web-demo/craco.config.js
  apps/web-demo/package-lock.json
  apps/web-demo/package.json
  apps/web-demo/public/favicon.ico
  apps/web-demo/public/index.html
  apps/web-demo/public/logo192.png
  apps/web-demo/public/logo512.png
  apps/web-demo/public/manifest.json
  apps/web-demo/public/robots.txt
  apps/web-demo/public/secrets.min.js
  apps/web-demo/public/serviceworker/sw.js
  apps/web-demo/src/App.css
  apps/web-demo/src/App.test.tsx
  apps/web-demo/src/App.tsx
  apps/web-demo/src/index.css
  apps/web-demo/src/index.tsx
  apps/web-demo/src/logo.svg
  apps/web-demo/src/react-app-env.d.ts
  apps/web-demo/src/reportWebVitals.ts
  apps/web-demo/src/service-worker.ts
  apps/web-demo/src/serviceWorkerRegistration.ts
  apps/web-demo/src/setupTests.ts
  apps/web-demo/tsconfig.json
  packages/sdk/CHANGELOG.md
Labels: 🔍 Ready for Review, size/M

#20 update release
  .changeset/large-frogs-tickle.md
  packages/sdk/package.json
Labels: 🔍 Ready for Review, size/XS

#24 chore: add prerelease
  .changeset/brave-pillows-deny.md
  .changeset/large-frogs-tickle.md
  .changeset/pre.json
  .github/workflows/pre-release.yml
  package.json
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
Labels: 🔍 Ready for Review, size/L

#25 doc: update readme
  .changeset/pre.json
  .changeset/spotty-geckos-pull.md
  README.md
  packages/sdk/readme.md
Labels: 🔍 Ready for Review, size/S

#34 Fix entry file
  .changeset/forty-cows-pull.md
  .changeset/pre.json
  .changeset/young-feet-pump.md
  package.json
  packages/sdk/package.json
  yarn.lock
Labels: 🔍 Ready for Review, size/M

#37 ci: bump version
  .changeset/pre.json
  .changeset/purple-dragons-mix.md
  packages/sdk/src/nft.ts
Labels: size/S

#43 fix: type fixes
  .changeset/pre.json
  .changeset/wicked-masks-hear.md
  packages/sdk/src/types.ts
Labels: 🔍 Ready for Review, size/S

#45 fix: resolve duplicate types
  .changeset/light-meals-battle.md
  .changeset/pre.json
  packages/sdk/src/nft/nft.service.ts
  packages/sdk/src/nft/types/index.ts
  packages/sdk/src/types.ts
Labels: 🔍 Ready for Review, size/M

#47 fix: use address from wallet
  .changeset/heavy-timers-care.md
  .changeset/pre.json
  packages/sdk/src/nft/nft.service.ts
  packages/sdk/src/nft/types/index.ts
Labels: 🔍 Ready for Review, size/M

#49 fix: remove duplicate types
  .changeset/pre.json
  .changeset/strong-lies-travel.md
  packages/sdk/src/types.ts
Labels: 🔍 Ready for Review, size/S

#51 fix: resolve bugs in swap
  .changeset/pre.json
  .changeset/rotten-humans-approve.md
  packages/sdk/package.json
  packages/sdk/src/common/utils.ts
  packages/sdk/src/index.ts
  packages/sdk/src/swap/debridge/debridgeSwapProvider.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/L

#53 fix: add get quote
  .changeset/lucky-onions-cry.md
  .changeset/pre.json
  packages/sdk/src/common/chain-ids.ts
  packages/sdk/src/factory/chain-provider.ts
  packages/sdk/src/swap/debridge/debridgeSwapProvider.ts
  packages/sdk/src/swap/debridge/types/index.ts
  packages/sdk/src/transaction/constants/transaction-status.ts
  packages/sdk/src/transaction/transaction.service.ts
Labels: 🔍 Ready for Review, size/L

#55 fix: resolve type error
  .changeset/old-files-matter.md
  .changeset/pre.json
  packages/sdk/src/swap/debridge/debridgeSwapProvider.ts
Labels: 🔍 Ready for Review, size/S

#58 ci: update release flow
  .changeset/pre.json
  .github/workflows/release.yml
  package.json
Labels: 🔍 Ready for Review, size/M

#63 Master
  .changeset/brave-pillows-deny.md
  .changeset/few-buckets-behave.md
  .changeset/forty-cows-pull.md
  .changeset/funny-apricots-jam.md
  .changeset/heavy-timers-care.md
  .changeset/light-meals-battle.md
  .changeset/lucky-onions-cry.md
  .changeset/moody-pots-arrive.md
  .changeset/old-files-matter.md
  .changeset/pre.json
  .changeset/purple-dragons-mix.md
  .changeset/rotten-humans-approve.md
  .changeset/spotty-geckos-pull.md
  .changeset/strong-lies-travel.md
  .changeset/tasty-pens-shave.md
  .changeset/wicked-masks-hear.md
  .changeset/young-feet-pump.md
  .github/workflows/release.yml
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  yarn.lock
Labels: 🔍 Ready for Review, size/L

#64 feat: updated auth service, added nvmrc and register service worker util
  .nvmrc
  packages/sdk/src/auth/auth.service.ts
  packages/sdk/src/auth/index.ts
  packages/sdk/src/auth/tryRegisterSW.ts
  packages/sdk/src/index.ts
Labels: ✅ Approved, size/M

#67 bump release version
  .changeset/heavy-planes-shop.md
  .changeset/pre.json
  .changeset/tidy-seas-punch.md
  .nvmrc
  apps/web-demo/CHANGELOG.md
  apps/web-demo/package.json
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/sdk/readme.md
  packages/sdk/src/auth/auth.service.js
  packages/sdk/src/auth/auth.service.ts
  packages/sdk/src/auth/index.ts
  packages/sdk/src/auth/tryRegisterSW.ts
  packages/sdk/src/common/utils.ts
  packages/sdk/src/factory/chain-provider.ts
  packages/sdk/src/index.ts
  packages/sdk/src/nft/nft.service.ts
  packages/sdk/src/swap/debridge/debridgeSwapProvider.ts
  packages/sdk/src/transaction/transaction.service.ts
  yarn.lock
Labels: 🔍 Ready for Review, size/XXL
